# Generated by Django 6.0.6 on 2026-07-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_name_signup_first_name_remove_signup_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
